#!/bin/bash

rm -f *.txt

#./router 1 2 1 2 3 2 2 2 1 3&

#sleep 1

./bridge 1 4&

sleep 1

#./bridge 2 5&

#sleep 1

./host 1 1 1 1 2 1 1&

sleep 1

./host 1 2 3 9 9 1 2 1 1 "Hello World"&

sleep 1

#./router 2 3 2 4 6&

#sleep 1

#./host 2 1 5 2 2 2 2 1 1 "This is a stupid simple network"&

#sleep 1
